# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/m64py/ui/input.ui'
#
# Created: Thu Dec  7 18:09:21 2017
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InputDialog(object):
    def setupUi(self, InputDialog):
        InputDialog.setObjectName("InputDialog")
        InputDialog.resize(858, 654)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(InputDialog.sizePolicy().hasHeightForWidth())
        InputDialog.setSizePolicy(sizePolicy)
        InputDialog.setMinimumSize(QtCore.QSize(858, 654))
        InputDialog.setWindowTitle("Mupen64Plus SDL Input Plugin")
        InputDialog.setToolTip("")
        self.gridLayout_17 = QtWidgets.QGridLayout(InputDialog)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.groupBox = QtWidgets.QGroupBox(InputDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    border: 1px solid #7F7F7F;\n"
"    border-radius: 3px;\n"
"    margin-top: 1ex; \n"
" }\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; \n"
"    padding: 0 2px;\n"
" }")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboController = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboController.sizePolicy().hasHeightForWidth())
        self.comboController.setSizePolicy(sizePolicy)
        self.comboController.setObjectName("comboController")
        self.horizontalLayout_4.addWidget(self.comboController)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 0, 0, 1, 1)
        self.comboDevice = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboDevice.sizePolicy().hasHeightForWidth())
        self.comboDevice.setSizePolicy(sizePolicy)
        self.comboDevice.setObjectName("comboDevice")
        self.gridLayout_7.addWidget(self.comboDevice, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 2, 1, 1, 1)
        self.comboMode = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboMode.sizePolicy().hasHeightForWidth())
        self.comboMode.setSizePolicy(sizePolicy)
        self.comboMode.setObjectName("comboMode")
        self.gridLayout_7.addWidget(self.comboMode, 2, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 1, 1, 1, 1)
        self.comboPlugin = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboPlugin.sizePolicy().hasHeightForWidth())
        self.comboPlugin.setSizePolicy(sizePolicy)
        self.comboPlugin.setObjectName("comboPlugin")
        self.gridLayout_7.addWidget(self.comboPlugin, 0, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 1, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkPlugged = QtWidgets.QCheckBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkPlugged.sizePolicy().hasHeightForWidth())
        self.checkPlugged.setSizePolicy(sizePolicy)
        self.checkPlugged.setObjectName("checkPlugged")
        self.gridLayout.addWidget(self.checkPlugged, 0, 0, 1, 1)
        self.checkMouse = QtWidgets.QCheckBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkMouse.sizePolicy().hasHeightForWidth())
        self.checkMouse.setSizePolicy(sizePolicy)
        self.checkMouse.setObjectName("checkMouse")
        self.gridLayout.addWidget(self.checkMouse, 1, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_15.addWidget(self.label_3, 0, 0, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(13, 14, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem4, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_15.addWidget(self.label_13, 0, 3, 1, 1)
        self.spinDeadzoneX = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinDeadzoneX.sizePolicy().hasHeightForWidth())
        self.spinDeadzoneX.setSizePolicy(sizePolicy)
        self.spinDeadzoneX.setMaximum(65535)
        self.spinDeadzoneX.setObjectName("spinDeadzoneX")
        self.gridLayout_15.addWidget(self.spinDeadzoneX, 0, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_15.addWidget(self.label_14, 0, 5, 1, 1)
        self.spinDeadzoneY = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinDeadzoneY.sizePolicy().hasHeightForWidth())
        self.spinDeadzoneY.setSizePolicy(sizePolicy)
        self.spinDeadzoneY.setMaximum(65535)
        self.spinDeadzoneY.setObjectName("spinDeadzoneY")
        self.gridLayout_15.addWidget(self.spinDeadzoneY, 0, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_15.addWidget(self.label_4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(31, 13, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem5, 1, 1, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_15.addWidget(self.label_15, 1, 3, 1, 1)
        self.spinPeakX = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinPeakX.sizePolicy().hasHeightForWidth())
        self.spinPeakX.setSizePolicy(sizePolicy)
        self.spinPeakX.setMaximum(65535)
        self.spinPeakX.setObjectName("spinPeakX")
        self.gridLayout_15.addWidget(self.spinPeakX, 1, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_15.addWidget(self.label_16, 1, 5, 1, 1)
        self.spinPeakY = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinPeakY.sizePolicy().hasHeightForWidth())
        self.spinPeakY.setSizePolicy(sizePolicy)
        self.spinPeakY.setMaximum(65535)
        self.spinPeakY.setObjectName("spinPeakY")
        self.gridLayout_15.addWidget(self.spinPeakY, 1, 6, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem6 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem6, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushL_Trig = InputButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushL_Trig.sizePolicy().hasHeightForWidth())
        self.pushL_Trig.setSizePolicy(sizePolicy)
        self.pushL_Trig.setMinimumSize(QtCore.QSize(0, 0))
        self.pushL_Trig.setAutoDefault(False)
        self.pushL_Trig.setObjectName("pushL_Trig")
        self.horizontalLayout_5.addWidget(self.pushL_Trig)
        self.label_12 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        spacerItem7 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.pushR_Trig = InputButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushR_Trig.sizePolicy().hasHeightForWidth())
        self.pushR_Trig.setSizePolicy(sizePolicy)
        self.pushR_Trig.setAutoDefault(False)
        self.pushR_Trig.setObjectName("pushR_Trig")
        self.horizontalLayout_6.addWidget(self.pushR_Trig)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.gridLayout_8.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem8, 0, 2, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_26 = QtWidgets.QLabel(self.groupBox_8)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 0, 1, 1, 1)
        self.pushDPad_U = InputButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushDPad_U.sizePolicy().hasHeightForWidth())
        self.pushDPad_U.setSizePolicy(sizePolicy)
        self.pushDPad_U.setAutoDefault(False)
        self.pushDPad_U.setObjectName("pushDPad_U")
        self.gridLayout_3.addWidget(self.pushDPad_U, 0, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_8)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 1, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 1, 1, 1, 1)
        self.pushDPad_D = InputButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushDPad_D.sizePolicy().hasHeightForWidth())
        self.pushDPad_D.setSizePolicy(sizePolicy)
        self.pushDPad_D.setAutoDefault(False)
        self.pushDPad_D.setObjectName("pushDPad_D")
        self.gridLayout_3.addWidget(self.pushDPad_D, 1, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_8)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 2, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 2, 1, 1, 1)
        self.pushDPad_L = InputButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushDPad_L.sizePolicy().hasHeightForWidth())
        self.pushDPad_L.setSizePolicy(sizePolicy)
        self.pushDPad_L.setAutoDefault(False)
        self.pushDPad_L.setObjectName("pushDPad_L")
        self.gridLayout_3.addWidget(self.pushDPad_L, 2, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_8)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 3, 0, 1, 1)
        self.pushDPad_R = InputButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushDPad_R.sizePolicy().hasHeightForWidth())
        self.pushDPad_R.setSizePolicy(sizePolicy)
        self.pushDPad_R.setAutoDefault(False)
        self.pushDPad_R.setObjectName("pushDPad_R")
        self.gridLayout_3.addWidget(self.pushDPad_R, 3, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem12, 3, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.labelImage = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.labelImage.sizePolicy().hasHeightForWidth())
        self.labelImage.setSizePolicy(sizePolicy)
        self.labelImage.setMinimumSize(QtCore.QSize(360, 318))
        self.labelImage.setStyleSheet("QLabel {\n"
"    border: 1px solid #7F7F7F;\n"
"    border-radius: 3px;\n"
"    margin-top: 1ex; \n"
" }")
        self.labelImage.setText("")
        self.labelImage.setPixmap(QtGui.QPixmap(":/images/controller.svg"))
        self.labelImage.setScaledContents(True)
        self.labelImage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImage.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.labelImage.setObjectName("labelImage")
        self.gridLayout_8.addWidget(self.labelImage, 1, 1, 2, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushC_Button_U = InputButton(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushC_Button_U.sizePolicy().hasHeightForWidth())
        self.pushC_Button_U.setSizePolicy(sizePolicy)
        self.pushC_Button_U.setAutoDefault(False)
        self.pushC_Button_U.setObjectName("pushC_Button_U")
        self.gridLayout_5.addWidget(self.pushC_Button_U, 0, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.groupBox_9)
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 2, 0, 1, 1)
        self.pushC_Button_R = InputButton(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushC_Button_R.sizePolicy().hasHeightForWidth())
        self.pushC_Button_R.setSizePolicy(sizePolicy)
        self.pushC_Button_R.setAutoDefault(False)
        self.pushC_Button_R.setObjectName("pushC_Button_R")
        self.gridLayout_5.addWidget(self.pushC_Button_R, 3, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem13, 0, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem14, 1, 1, 1, 1)
        self.pushC_Button_L = InputButton(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushC_Button_L.sizePolicy().hasHeightForWidth())
        self.pushC_Button_L.setSizePolicy(sizePolicy)
        self.pushC_Button_L.setAutoDefault(False)
        self.pushC_Button_L.setObjectName("pushC_Button_L")
        self.gridLayout_5.addWidget(self.pushC_Button_L, 2, 2, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.groupBox_9)
        self.label_48.setObjectName("label_48")
        self.gridLayout_5.addWidget(self.label_48, 3, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem15, 3, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_9)
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 0, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem16, 2, 1, 1, 1)
        self.pushC_Button_D = InputButton(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushC_Button_D.sizePolicy().hasHeightForWidth())
        self.pushC_Button_D.setSizePolicy(sizePolicy)
        self.pushC_Button_D.setAutoDefault(False)
        self.pushC_Button_D.setObjectName("pushC_Button_D")
        self.gridLayout_5.addWidget(self.pushC_Button_D, 1, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.groupBox_9)
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 1, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_9, 1, 2, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_50 = QtWidgets.QLabel(self.groupBox_10)
        self.label_50.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName("label_50")
        self.gridLayout_4.addWidget(self.label_50, 0, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem17, 0, 1, 1, 1)
        self.pushY_Axis_U = InputButton(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushY_Axis_U.sizePolicy().hasHeightForWidth())
        self.pushY_Axis_U.setSizePolicy(sizePolicy)
        self.pushY_Axis_U.setAutoDefault(False)
        self.pushY_Axis_U.setObjectName("pushY_Axis_U")
        self.gridLayout_4.addWidget(self.pushY_Axis_U, 0, 2, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.groupBox_10)
        self.label_51.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_51.setObjectName("label_51")
        self.gridLayout_4.addWidget(self.label_51, 1, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem18, 1, 1, 1, 1)
        self.pushY_Axis_D = InputButton(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushY_Axis_D.sizePolicy().hasHeightForWidth())
        self.pushY_Axis_D.setSizePolicy(sizePolicy)
        self.pushY_Axis_D.setAutoDefault(False)
        self.pushY_Axis_D.setObjectName("pushY_Axis_D")
        self.gridLayout_4.addWidget(self.pushY_Axis_D, 1, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.groupBox_10)
        self.label_49.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_49.setObjectName("label_49")
        self.gridLayout_4.addWidget(self.label_49, 2, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem19, 2, 1, 1, 1)
        self.pushX_Axis_L = InputButton(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushX_Axis_L.sizePolicy().hasHeightForWidth())
        self.pushX_Axis_L.setSizePolicy(sizePolicy)
        self.pushX_Axis_L.setAutoDefault(False)
        self.pushX_Axis_L.setObjectName("pushX_Axis_L")
        self.gridLayout_4.addWidget(self.pushX_Axis_L, 2, 2, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.groupBox_10)
        self.label_52.setObjectName("label_52")
        self.gridLayout_4.addWidget(self.label_52, 3, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem20, 3, 1, 1, 1)
        self.pushX_Axis_R = InputButton(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushX_Axis_R.sizePolicy().hasHeightForWidth())
        self.pushX_Axis_R.setSizePolicy(sizePolicy)
        self.pushX_Axis_R.setAutoDefault(False)
        self.pushX_Axis_R.setObjectName("pushX_Axis_R")
        self.gridLayout_4.addWidget(self.pushX_Axis_R, 3, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_10, 2, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem21, 0, 1, 1, 1)
        self.pushB_Button = InputButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushB_Button.sizePolicy().hasHeightForWidth())
        self.pushB_Button.setSizePolicy(sizePolicy)
        self.pushB_Button.setAutoDefault(False)
        self.pushB_Button.setObjectName("pushB_Button")
        self.gridLayout_6.addWidget(self.pushB_Button, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem22, 1, 1, 1, 1)
        self.pushA_Button = InputButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushA_Button.sizePolicy().hasHeightForWidth())
        self.pushA_Button.setSizePolicy(sizePolicy)
        self.pushA_Button.setAutoDefault(False)
        self.pushA_Button.setObjectName("pushA_Button")
        self.gridLayout_6.addWidget(self.pushA_Button, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 2, 0, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem23, 2, 1, 1, 1)
        self.pushMempak = InputButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushMempak.sizePolicy().hasHeightForWidth())
        self.pushMempak.setSizePolicy(sizePolicy)
        self.pushMempak.setAutoDefault(False)
        self.pushMempak.setObjectName("pushMempak")
        self.gridLayout_6.addWidget(self.pushMempak, 2, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 3, 0, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem24, 3, 1, 1, 1)
        self.pushRumblepak = InputButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushRumblepak.sizePolicy().hasHeightForWidth())
        self.pushRumblepak.setSizePolicy(sizePolicy)
        self.pushRumblepak.setAutoDefault(False)
        self.pushRumblepak.setObjectName("pushRumblepak")
        self.gridLayout_6.addWidget(self.pushRumblepak, 3, 2, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_5, 2, 2, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem25, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushStart = InputButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushStart.sizePolicy().hasHeightForWidth())
        self.pushStart.setSizePolicy(sizePolicy)
        self.pushStart.setMinimumSize(QtCore.QSize(0, 0))
        self.pushStart.setAutoDefault(False)
        self.pushStart.setObjectName("pushStart")
        self.horizontalLayout_2.addWidget(self.pushStart)
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_2)
        spacerItem26 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem26)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.pushZ_Trig = InputButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushZ_Trig.sizePolicy().hasHeightForWidth())
        self.pushZ_Trig.setSizePolicy(sizePolicy)
        self.pushZ_Trig.setAutoDefault(False)
        self.pushZ_Trig.setObjectName("pushZ_Trig")
        self.horizontalLayout_3.addWidget(self.pushZ_Trig)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_3)
        self.gridLayout_8.addLayout(self.horizontalLayout_8, 3, 1, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(208, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem27, 3, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_8)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        self.gridLayout_17.addWidget(self.groupBox, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.statusLabel = QtWidgets.QLabel(InputDialog)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout.addWidget(self.statusLabel)
        spacerItem28 = QtWidgets.QSpacerItem(288, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem28)
        self.pushButton = QtWidgets.QPushButton(InputDialog)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout_17.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(InputDialog)
        self.pushButton.clicked.connect(InputDialog.close)
        QtCore.QMetaObject.connectSlotsByName(InputDialog)

    def retranslateUi(self, InputDialog):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox.setTitle(_translate("InputDialog", "Input-SDL-Control"))
        self.label_17.setText(_translate("InputDialog", "Plugin"))
        self.label_19.setText(_translate("InputDialog", "Mode"))
        self.label_18.setText(_translate("InputDialog", "Device"))
        self.checkPlugged.setText(_translate("InputDialog", "Plugged"))
        self.checkMouse.setText(_translate("InputDialog", "Mouse"))
        self.label_3.setText(_translate("InputDialog", "AnalogDeadzone"))
        self.label_13.setText(_translate("InputDialog", "X:"))
        self.label_14.setText(_translate("InputDialog", "Y:"))
        self.label_4.setText(_translate("InputDialog", "AnalogPeak"))
        self.label_15.setText(_translate("InputDialog", "X:"))
        self.label_16.setText(_translate("InputDialog", "Y:"))
        self.pushL_Trig.setText(_translate("InputDialog", "Select..."))
        self.label_12.setText(_translate("InputDialog", "L Trigger"))
        self.label_11.setText(_translate("InputDialog", "R Trigger"))
        self.pushR_Trig.setText(_translate("InputDialog", "Select..."))
        self.groupBox_8.setTitle(_translate("InputDialog", "Digital Pad"))
        self.label_26.setText(_translate("InputDialog", "Up"))
        self.pushDPad_U.setText(_translate("InputDialog", "Select..."))
        self.label_25.setText(_translate("InputDialog", "Down"))
        self.pushDPad_D.setText(_translate("InputDialog", "Select..."))
        self.label_28.setText(_translate("InputDialog", "Left"))
        self.pushDPad_L.setText(_translate("InputDialog", "Select..."))
        self.label_27.setText(_translate("InputDialog", "Right"))
        self.pushDPad_R.setText(_translate("InputDialog", "Select..."))
        self.groupBox_9.setTitle(_translate("InputDialog", "C - Buttons"))
        self.pushC_Button_U.setText(_translate("InputDialog", "Select..."))
        self.label_47.setText(_translate("InputDialog", "Left"))
        self.pushC_Button_R.setText(_translate("InputDialog", "Select..."))
        self.pushC_Button_L.setText(_translate("InputDialog", "Select..."))
        self.label_48.setText(_translate("InputDialog", "Right"))
        self.label_45.setText(_translate("InputDialog", "Up"))
        self.pushC_Button_D.setText(_translate("InputDialog", "Select..."))
        self.label_46.setText(_translate("InputDialog", "Down"))
        self.groupBox_10.setTitle(_translate("InputDialog", "Analog Stick"))
        self.label_50.setText(_translate("InputDialog", "Up"))
        self.pushY_Axis_U.setText(_translate("InputDialog", "Select..."))
        self.label_51.setText(_translate("InputDialog", "Down"))
        self.pushY_Axis_D.setText(_translate("InputDialog", "Select..."))
        self.label_49.setText(_translate("InputDialog", "Left"))
        self.pushX_Axis_L.setText(_translate("InputDialog", "Select..."))
        self.label_52.setText(_translate("InputDialog", "Right"))
        self.pushX_Axis_R.setText(_translate("InputDialog", "Select..."))
        self.groupBox_5.setTitle(_translate("InputDialog", "Buttons"))
        self.label_7.setText(_translate("InputDialog", "B Button"))
        self.pushB_Button.setText(_translate("InputDialog", "Select..."))
        self.label_8.setText(_translate("InputDialog", "A Button"))
        self.pushA_Button.setText(_translate("InputDialog", "Select..."))
        self.label_9.setText(_translate("InputDialog", "Mempak"))
        self.pushMempak.setText(_translate("InputDialog", "Select..."))
        self.label_10.setText(_translate("InputDialog", "Rumblepak"))
        self.pushRumblepak.setText(_translate("InputDialog", "Select..."))
        self.pushStart.setText(_translate("InputDialog", "Select..."))
        self.label_5.setText(_translate("InputDialog", "Start"))
        self.label_6.setText(_translate("InputDialog", "Z Trigger"))
        self.pushZ_Trig.setText(_translate("InputDialog", "Select..."))
        self.pushButton.setText(_translate("InputDialog", "&Close"))

from m64py.ui.inputbutton import InputButton
from . import images_rc
